# Liip Imagine
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        60x60:
            quality: 100
            filters:
                thumbnail: { size: [ 60, 60 ], mode: outbound }

# Vich
vich_uploader:
    db_driver: orm
    mappings:
        page:
            uri_prefix:         /uploads/images/page
            upload_destination: %kernel.root_dir%/../web/uploads/images/page
            namer:              vich_uploader.namer_uniqid
